// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmurfGame.DAL;

#nullable disable

namespace SmurfGame.DAL.Migrations
{
    [DbContext(typeof(SmurfGameContext))]
    [Migration("20260404235034_AddSmurfBestTime")]
    partial class AddSmurfBestTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmurfGame.BL.Entities.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("X", "Y")
                        .HasDatabaseName("IX_Creatures_Position");

                    b.ToTable("Creatures", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthBoost")
                        .HasColumnType("int");

                    b.Property<bool>("IsConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("X", "Y")
                        .HasDatabaseName("IX_Items_Position");

                    b.ToTable("Items", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Azrael", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Creature");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.ToTable("Azraels");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Bug", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Creature");

                    b.Property<int>("AttackDamage")
                        .HasColumnType("int");

                    b.ToTable("Bugs", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Smurf", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Creature");

                    b.Property<int?>("BestTime")
                        .HasColumnType("int");

                    b.Property<bool>("IsInForest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.ToTable("Smurfs", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Berry", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.ToTable("Berries", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.BluePotion", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.ToTable("BluePotions", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Coin", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.RedPotion", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.Property<int>("BoostMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.ToTable("RedPotions", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.SpeedBuff", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.Property<int>("SpeedBoostAmount")
                        .HasColumnType("int");

                    b.ToTable("SpeedBuffs");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.BzzFly", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Bug");

                    b.Property<int>("FlySpeed")
                        .HasColumnType("int");

                    b.ToTable("BzzFlies", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Spider", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Bug");

                    b.Property<int>("LegCount")
                        .HasColumnType("int");

                    b.ToTable("Spiders", (string)null);
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Bug", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Creature", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.Bug", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Smurf", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Creature", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.Smurf", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Berry", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.Berry", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.BluePotion", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.BluePotion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Coin", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.Coin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.RedPotion", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.RedPotion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.SpeedBuff", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.SpeedBuff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.BzzFly", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Bug", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.BzzFly", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Spider", b =>
                {
                    b.HasOne("SmurfGame.BL.Entities.Bug", null)
                        .WithOne()
                        .HasForeignKey("SmurfGame.BL.Entities.Spider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
