// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmurfGame.DAL;

#nullable disable

namespace SmurfGame.DAL.Migrations
{
    [DbContext(typeof(SmurfGameContext))]
    [Migration("20260224201338_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmurfGame.BL.Entities.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("X", "Y")
                        .HasDatabaseName("IX_Creatures_Position");

                    b.ToTable("Creatures", (string)null);

                    b.HasDiscriminator<string>("CreatureType").HasValue("Creature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HealthBoost")
                        .HasColumnType("int");

                    b.Property<bool>("IsConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("X", "Y")
                        .HasDatabaseName("IX_Items_Position");

                    b.ToTable("Items", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.BzzFly", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Creature");

                    b.Property<int>("AttackDamage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BzzFly");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Smurf", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Creature");

                    b.Property<bool>("IsInForest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasDiscriminator().HasValue("Smurf");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Spider", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Creature");

                    b.Property<int>("AttackDamage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Spider");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.Berry", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.HasDiscriminator().HasValue("Berry");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.BluePotion", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.HasDiscriminator().HasValue("BluePotion");
                });

            modelBuilder.Entity("SmurfGame.BL.Entities.RedPotion", b =>
                {
                    b.HasBaseType("SmurfGame.BL.Entities.Item");

                    b.Property<int>("BoostMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.HasDiscriminator().HasValue("RedPotion");
                });
#pragma warning restore 612, 618
        }
    }
}
